language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
# Build
- docker build -t udagram-api-feed /udagram-api-feed
- docker build -t udagram-api-user /udagram-api-user
- docker build -t udagram-frontend /udagram-frontend
- docker build -t udagram-reverseproxy /udagram-reverseproxy

# Tagging
- docker tag udagram-api-feed ugoiloh/udagram-api-feed:v1
- docker tag udagram-api-user ugoiloh/udagram-api-user:v1
- docker tag udagram-frontend ugoiloh/udagram-frontend:v1
- docker tag udagram-reverseproxy ugoiloh/udagram-reverseproxy:v1

after_success:
# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push ugoiloh/udagram-api-feed:v1
- docker push ugoiloh/udagram-api-user:v1
- docker push ugoiloh/udagram-frontend:v1
- docker push ugoiloh/udagram-reverseproxy:v1

